base:
  buffer:
    initial_size: 1024
    max_size: 65536
    growth_factor: 2

log:
  basename: logs/server
  roll_size: 1048576
  flush_interval: 1
  roll_mode: SIZE_HOURLY
  enable_file: true
  enable_async: true   # false=同步，true=异步
  file_level: DEBUG
  console_level: WARN

network:
  ip: 127.0.0.1
  port: 8080
  epoll_mode: "LT"  # 可选 "ET" 或 "LT"，ET=边缘触发，LT=水平触发，默认LT
  thread_pool:
    thread_num: 3
    queue_size: 1000
    keep_alive_time: 60
    max_idle_threads: 5
    min_idle_threads: 1
